config/routes.rb
Curatedby::Application.routes.draw do

 match '/home' => 'home#index', :via => :get
 match '/overview' => 'home#overview', :via => :get
 match '/contact' => 'home#contact', :via => :get

  resources :arts

  resources :museums

   root :to => 'museums#index'

end

app/models/art.rb
# == Schema Information
#
# Table name: arts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  style      :string(255)
#  medium     :string(255)
#  created_on :date
#  artist     :string(255)
#  photo      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Art < ActiveRecord::Base
  attr_accessible :artist, :created_on, :medium, :name, :photo, :style, :museum_id, :remote_photo_url
  belongs_to :museum
  mount_uploader :photo, SnapshotUploader
end

app/models/museum.rb
# == Schema Information
#
# Table name: museums
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  art_id     :integer
#

class Museum < ActiveRecord::Base
  attr_accessible :address, :name, :photo, :remote_photo_url, :art_ids
  has_many :arts
  mount_uploader :photo, SnapshotUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @arts }
    end
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
    @art = Art.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @art }
    end
  end

  # GET /arts/new
  # GET /arts/new.json
  def new
    @art = Art.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @art }
    end
  end

  # GET /arts/1/edit
  def edit
    @art = Art.find(params[:id])
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(params[:art])

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render json: @art, status: :created, location: @art }
      else
        format.html { render action: "new" }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /arts/1
  # PUT /arts/1.json
  def update
    @art = Art.find(params[:id])

    respond_to do |format|
      if @art.update_attributes(params[:art])
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art = Art.find(params[:id])
    @art.destroy

    respond_to do |format|
      format.html { redirect_to arts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 

def index 

end 

def overview 

end 

def contact

end 


end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  # GET /museums
  # GET /museums.json
  def index
    @museums = Museum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @museums }
    end
  end

  # GET /museums/1
  # GET /museums/1.json
  def show
    @museum = Museum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @museum }
    end
  end

  # GET /museums/new
  # GET /museums/new.json
  def new
    @museum = Museum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @museum }
    end
  end

  # GET /museums/1/edit
  def edit
    @museum = Museum.find(params[:id])
  end

  # POST /museums
  # POST /museums.json
  def create
    @museum = Museum.new(params[:museum])

    respond_to do |format|
      if @museum.save
        format.html { redirect_to @museum, notice: 'Museum was successfully created.' }
        format.json { render json: @museum, status: :created, location: @museum }
      else
        format.html { render action: "new" }
        format.json { render json: @museum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /museums/1
  # PUT /museums/1.json
  def update
    @museum = Museum.find(params[:id])

    respond_to do |format|
      if @museum.update_attributes(params[:museum])
        format.html { redirect_to @museum, notice: 'Museum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @museum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /museums/1
  # DELETE /museums/1.json
  def destroy
    @museum = Museum.find(params[:id])
    @museum.destroy

    respond_to do |format|
      format.html { redirect_to museums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_login(user)
   if user 
   	link_to user.email + " " + number_to_currency(user.balance).to_s, logout_path
   else
   	link_to "Login", login_path
   end  	
  end


def create_navlink(name, url)
      # <li class="active"><a href="#">Home</a></li>
      
      cname = name.downcase
      is_active = cname == controller.controller_name
      active = is_active ? 'active' : ''

      link = link_to(name, url)
      "<li class=\"#{active}\">#{link}</li>".html_safe
end



end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/views/arts/_form.html.erb
<%= form_for(@art) do |f| %>
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :medium %><br />
    <%= f.text_field :medium %>
  </div>
  <div class="field">
    <%= f.label :created_on %><br />
    <%= f.date_select :created_on %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
    <%= f.text_field :remote_photo_url %>
  </div>
 
  <div class="field">
    <%= f.label :museum_id %><br />
    <%= f.select :museum_id, Museum.all.map{|a|[a.name, a.id]}, {:prompt =>"Select the museum to which the art belongs"} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing art</h1>

<%= render 'form' %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
<h1>Browse Art</h1>

<% @arts.each do |art| %>
  <div class="art-listing">
    <%= image_tag(art.photo) %>
    <h2><%= art.name %></h2>
    <li>Style: <%= art.style %></li>
    <li>Medium: <%= art.medium %></li>
    <li>Created: <%= art.created_on %></li>
    <li>Artist: <%= art.artist %></li>
    <li>Museum: <%= art.museum.name %></li>
    <li><%= link_to 'Show', art %>
    <%= link_to 'Edit', edit_art_path(art) %>
   </li>
    </div>

<% end %>

<br />

<div class="clear">
<%= link_to 'New Art', new_art_path %>
</div>

app/views/arts/new.html.erb
<h1>New art</h1>

<%= render 'form' %>

<%= link_to 'Back', arts_path %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @art.name %></h1>
  
<%= image_tag(@art.photo) %>

<p>
  <b>Style:</b>
  <%= @art.style %>
</p>

<p>
  <b>Medium:</b>
  <%= @art.medium %>
</p>

<p>
  <b>Created on:</b>
  <%= @art.created_on %>
</p>

<p>
  <b>Artist:</b>
  <%= @art.artist %>
</p>

<p>
<b>Museum:</b>
  <%= @art.museum.name %>
</p>

<%= link_to 'Edit', edit_art_path(@art) %> |
<%= link_to 'Back', arts_path %> |
<%= link_to 'Destroy', @art, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/home/index.html.erb
<div class="span3">
  <h1>CuratedBy</h1>
  <em>Find the Art You Want</em>
 <br/>
</div>

<div class="span9">
	<%= image_tag('jowoffinden7.jpg')%>
  
</div>

 <a class='btn btn-inverse btn-large' href='/arts'>Browse Art</a>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Curatedby</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
		<div class="span12">
          <div class="navbar">
             <div class="navbar-inner">
               <a class="brand" href="/">CuratedBy</a>
               <ul class="nav">
                    <%= create_navlink('Home', home_path) %>
                    <%= create_navlink('Museums', museums_path) %>
                    <%= create_navlink('Art', arts_path) %>
                </ul>
             </div>
            </div>
          </div>
    </div>
    
        <div class="row">
                <div class="span12">
                <%= yield %>
            </div>
        </div>

        
        </div>

</body>
</html>

</body>
</html>

app/views/museums/_form.html.erb
<%= form_for(@museum) do |f| %>
  <% if @museum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@museum.errors.count, "error") %> prohibited this museum from being saved:</h2>

      <ul>
      <% @museum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>

 <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
    <%= f.text_field :remote_photo_url %>
  </div>

<div class="field">
    <% Art.all.each do |art| %>
    <%=art.name%>
    <%= check_box_tag 'museum[art_ids]{}', art.id, @museum.arts.include?(art)%>
    <%end%>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/museums/edit.html.erb
<h1>Editing museum</h1>

<%= render 'form' %>

<%= link_to 'Show', @museum %> |
<%= link_to 'Back', museums_path %>

app/views/museums/index.html.erb
<h1>Museums</h1>

<% @museums.each do |museum| %>
<div class="museum-listing">
   <%= link_to image_tag(museum.photo), museum_path(museum) %>
   <h2><%= museum.name %></h2>
   <li><%= museum.address %></li>
<%= link_to 'View Art', museum_path(museum) %> |
<%= link_to 'Delete Museum', museum, method: :delete, data: { confirm: 'Are you sure?' } %>   
</div>
<% end %>

<br />

<div class="clear">
<%= link_to 'New Museum', new_museum_path %>
</div>

app/views/museums/new.html.erb
<h1>New museum</h1>

<%= render 'form' %>

<%= link_to 'Back', museums_path %>

app/views/museums/show.html.erb
<p id="notice"><%= notice %></p>


<%= image_tag(@museum.photo) %>

<h1><%= @museum.name %></h1>

<p>
  <%= @museum.address %>
</p>

<h3>Art in this museum</h3>

<p>
<%= @museum.art_id %>
 <%@museum.arts.each do |s|%>
 <div class="thumbnail">
        <li><%= link_to(image_tag(s.photo), art_path(s))%></li>
 </div>
    <%end%>
</ul>
</p>

<div class="clear">
<%= link_to 'Edit Museum Listing', edit_museum_path(@museum) %> |
<%= link_to 'View All Museums', museums_path %> |
<%= link_to 'Delete This Museum', @museum, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>